### ISSUE TITLE
Improve data pipeline so it behaves like a wildcard

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-paragraph#3]
Every HTML block element which doesn't have a corresponding feature in CKEditor should be accepted by the paragraph feature, what ultimately will convert those blocks to paragraphs. This is an important feature especially for pasting.

**Comment by scofalik** [comment]
This came up when launching first demoable version of CKEditor5. Paragraph feature should define "default" converter with low priority that will convert _things_ to paragraphs.

We have to decide, how to define those _things_. We may either come up with configurable list of block HTML tags or decide to convert all unrecognized stuff to paragraphs. The first solution will end up with text cut-out if we omit some tags. The second solution will end up in paragraphs were inline elements were before, which may destroy the content completly.

Or we come up with a better idea, but right now I don't have one.

**Comment by Reinmar** [comment]
> We have to decide, how to define those things. We may either come up with configurable list of block HTML tags or decide to convert all unrecognized stuff to paragraphs.

Ideally, we should know what was the computed `display` style of pasted or inserted in any other way elements, but such information is totally impossible to obtain.

Therefore, I'm all for a list (eventually configurable in some way) of elements that should be considered as blocks and transformed to paragraphs. All other elements should simply be ignored. That should cause **unwrapping** their content from them, *not* cutting out some pieces.

This is only future-proof solution which will handle custom elements (because you can always configure the feature how to handle them).

**Comment by scofalik** [comment]
Unwrapping will work as far as the text eventually ends up in a block element (`Schema` for most editors will allow `$text` only in `$block`).

> Ideally, we should know what was the computed display style of pasted or inserted in any other way elements, but such information is totally impossible to obtain.

Is it really impossible? We have `Window.getComputedStyle()`. However I understand it would be difficult to use, we would need to append contents somewhere and only then read computed styles and start pasting into editor and the conversion... Then, we would still lose some info because source website had their additional csses... So I guess it would be far from perfect.

**Comment by Reinmar** [comment]
> Unwrapping will work as far as the text eventually ends up in a block element (Schema for most editors will allow $text only in $block).

That's exactly what need to be coded. E.g. you have a list:

```html
<ul>
  <li>Foo</li>
  <li>Bar</li>
</ul>
```

When there's no list feature, this should be transformed to two paragraphs. It means that `<li>`s has to be converted to `<p>`s. The same with `<tr>`s in tables (not `<td>`s).

> Is it really impossible? We have Window.getComputedStyle().

But we can only learn how such content would be styled on our website, when put in some generic location like a `<body>`. The content may come from a different website or from a specific place in DOM where it had different styles applied. So what we need are those original styles, not some random ones.

Besides, AFAIK it'd be really hard to get computed styles anyway, because you'd need to inject the content somewhere, risking serious XSS issues.

**Comment by scofalik** [comment]
> That's exactly what need to be coded. (...)  The same with `<tr>`s in tables (not `<td>`s).
Yes, yes. Do you know there is a test that checks if such converter is possible? It is in `advanced-converters.js`.

Well, even pasting HTML into blank `<body>` and checking computed style `display` would be more safe than creating a list of elements that we think should be `block` or `inline` .However, XSS issues convinced me that it's bad idea to try checking computed styles :P. Also there is the case that not all elements might be treated equal, so we need some flexibility anyway. I am fine with list.

**Comment by Reinmar** [comment]
There are more issues AFAIK – like – you have to actually show that piece of content (it can be positioned beyond your viewport though) to calculate styles. The content will trigger loading images, scripts, videos, etc. Etc etc. In general – that's a very bad idea :D.

From the other perspective, it's not so good idea as well. How's our list worse than a browser's list? Browser will style only a specific set of elements to be blocks. We can, with a really high certainty and "future-proofness", create such a list too.

But most importantly, no one will actually care. I mean – some day someone will report this... maybe. But if we make the list configurable that will deserve `resolution:invalid` or `resolution:wontfix`.
