### ISSUE TITLE
Introduce ParagraphButtonUI

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-paragraph#33]
ParagraphButtonUI should be created, similar to: https://github.com/ckeditor/ckeditor5-heading/issues/104, with the default icon for the paragraph. Plugin should be optional, not required by Paragaph plugin.

**Comment by ma2ciek** [comment]
We have a F2F talk about providing translations for the plugin. Both `ckeditor5-heading` and `ckeditor5-paragraph` packages should use `paragraph`, so the `paragraph` *msgid* should be moved to the `ckeditor5-core`. (`ckeditor5-core` is the core package for translations and should be used to prevent duplications). But removing the `paragraph` *msgid* from `ckeditor5-heading` will cause removing all translations for `paragraph`.

The case has already popped out - https://github.com/ckeditor/ckeditor5-dev/issues/376.

**Comment by Reinmar** [comment]
Can we use the translation available in the heading package for now? Or is the scope limited to each package + core?

**Comment by ma2ciek** [comment]
We check for duplications while we're gathering sources to upload: https://github.com/ckeditor/ckeditor5-dev/blob/6c69057249c8db63f0342fce7643b8707d3dc634/packages/ckeditor5-dev-env/tests/translations/collect-utils.js#L227-L239

**Comment by Reinmar** [comment]
But it's about repeated context. And is the paragraph feature able to use the translation from the heading feature? Or does that fall into the "repeated context" check?

**Comment by Reinmar** [comment]
BTW, I may avoid using `translations:collect` for a while, until we figure out ckeditor/ckeditor5-dev#376. So, for now, it's just a question of whether it's going to build :D

**Comment by ma2ciek** [comment]
It should build, translations are stored in the `key -> translation` for now.
