### ISSUE TITLE
Add configuration to change P to DIV

### ISSUE THREAD

**Issue by istanishev** [ckeditor/ckeditor5-paragraph#44]
In some cases, using P element causes inconveniences as it cannot be nested inside itself. It would be nice if this plugin has configuration on what HTML tag to use to represent the paragraph model.

**Comment by Mgsy** [comment]
Hello, we don't provide such configuration, but if you really want to make this change, you can do it by yourself, just modify current paragraph plugin's code or create a new plugin. 

You need to read about [Schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html). Reading this [discussion](https://github.com/ckeditor/ckeditor5/issues/1314) also should give you better understanding how to do it.

**Comment by istanishev** [comment]
It is true that I can create a different plugin, but it might be since this plugin is pretty basic, a lot of other plugins depend on it. Wouldn't this cause a problem?
